[project]
name = "mcp-rag-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sehyeon", email = "161838058+BEEN2984@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-mcp-server>=0.6.1",
    "langchain-openai>=1.6.2",
    "mcp-use>=1.7.1",
]

[project.scripts]
mcp-rag-example = "mcp_rag_example:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
